use meatballs;
insert into admin ( staff_id,  location,  yrs_exp,  training) Values
(1, 'Montreal', 0, 'Spread Sheet , Linux, Mobile'),
(2, 'Montreal', 0, 'Windows 7, Golf, Linux'),
(3, 'Montreal', 2, 'Windows 7'),
(4, 'Montreal', 0, 'Ubuntu, Walking and Chewing BubbleGum, Advanced Leadership'),
(5, 'Montreal', 2, 'Windows 98, Ubuntu, Mobile, Advanced Leadership'),
(6, 'Montreal', 3, 'Windows 7'),
(7, 'Montreal', 2, 'Walking and Chewing BubbleGum, Ubuntu'),
(8, 'Montreal', 4, 'Windows 98'),
(9, 'Montreal', 4, 'Money Management'),
(10, 'Montreal', 2, 'Advanced Leadership'),
(11, 'Montreal', 2, 'Counting Money'),
(12, 'Montreal', 0, 'Windows 7, Linux'),
(13, 'Montreal', 1, 'Windows 7, Golf'),
(14, 'Montreal', 0, 'Spread Sheet , Golf, Advanced Leadership'),
(15, 'Montreal', 4, 'Spread Sheet , Mobile'),
(16, 'Montreal', 1, 'Money Management'),
(17, 'Montreal', 1, 'Linux'),
(18, 'Montreal', 3, 'Advanced Talking'),
(19, 'Montreal', 0, 'Ubuntu'),
(20, 'Montreal', 0, 'Word Processing'),
(21, 'Montreal', 2, 'Money Management, Golf'),
(22, 'Montreal', 0, 'Word Processing'),
(23, 'Montreal', 0, 'Mobile'),
(24, 'Montreal', 2, 'Windows 98'),
(25, 'Montreal', 4, 'Walking and Chewing BubbleGum, Linux, Word Processing'),
(26, 'Montreal', 4, 'Mobile, Spread Sheet '),
(27, 'Montreal', 4, 'Advanced Leadership, Money Management, Ubuntu'),
(28, 'Montreal', 2, 'Spread Sheet , Advanced Lion Taming, Windows 98'),
(29, 'Montreal', 0, 'Golf, Windows 98, Linux, Walking and Chewing BubbleGum'),
(30, 'Montreal', 2, 'Money Management'),
(31, 'Montreal', 0, 'Advanced Lion Taming, Advanced Talking'),
(32, 'Montreal', 0, 'Linux'),
(33, 'Montreal', 0, 'Advanced Lion Taming, Advanced Lion Taming, Windows 7'),
(34, 'Montreal', 2, 'Counting Money, Linux, Windows 98'),
(35, 'Montreal', 4, 'Windows 98, Mobile, Word Processing'),
(36, 'Montreal', 2, 'Advanced Lion Taming, Advanced Lion Taming'),
(37, 'Montreal', 1, 'Linux'),
(38, 'Montreal', 2, 'Advanced Lion Taming, Advanced Lion Taming'),
(39, 'Montreal', 0, 'Linux, Word Processing, Word Processing');