use meatballs;
insert into admin ( staff_id,  location,  yrs_exp,  training) Values
(1, 'Montreal', 3, 'Ubuntu'),
(2, 'Montreal', 3, 'Golf'),
(3, 'Montreal', 4, 'Mobile, Advanced Lion Taming, Golf, Windows 7'),
(4, 'Montreal', 4, 'Ubuntu'),
(5, 'Montreal', 4, 'Walking and Chewing BubbleGum, Counting Money'),
(6, 'Montreal', 2, 'Advanced Leadership, Linux'),
(7, 'Montreal', 0, 'Windows 98, Advanced Lion Taming, Word Processing, Counting Money'),
(8, 'Montreal', 2, 'Windows 98, Advanced Lion Taming'),
(9, 'Montreal', 0, 'Golf'),
(10, 'Montreal', 0, 'Advanced Leadership, Windows 98, Spread Sheet'),
(11, 'Montreal', 4, 'Walking and Chewing BubbleGum, Word Processing, Linux, Walking and Chewing BubbleGum'),
(12, 'Montreal', 3, 'Golf, Money Management, Golf'),
(13, 'Montreal', 0, 'Mobile'),
(14, 'Montreal', 3, 'Advanced Leadership, Money Management, Walking and Chewing BubbleGum, Linux'),
(15, 'Montreal', 1, 'Advanced Lion Taming, Walking and Chewing BubbleGum'),
(16, 'Montreal', 1, 'Money Management'),
(17, 'Montreal', 3, 'Windows 7, Linux, Advanced Lion Taming, Word Processing'),
(18, 'Montreal', 2, 'Money Management, Counting Money'),
(19, 'Montreal', 0, 'Word Processing, Spread Sheet, Mobile, Advanced Talking'),
(20, 'Montreal', 4, 'Money Management, Counting Money'),
(21, 'Montreal', 0, 'Windows 98, Money Management, Linux'),
(22, 'Montreal', 3, 'Advanced Talking, Advanced Talking, Linux'),
(23, 'Montreal', 0, 'Word Processing, Advanced Leadership, Windows 98, Advanced Lion Taming'),
(24, 'Montreal', 0, 'Walking and Chewing BubbleGum, Advanced Talking, Windows 7'),
(25, 'Montreal', 1, 'Advanced Talking, Linux'),
(26, 'Montreal', 2, 'Advanced Lion Taming'),
(27, 'Montreal', 3, 'Ubuntu, Windows 7'),
(28, 'Montreal', 4, 'Advanced Talking, Word Processing, Advanced Leadership, Mobile'),
(29, 'Montreal', 3, 'Walking and Chewing BubbleGum, Advanced Talking, Golf'),
(30, 'Montreal', 3, 'Ubuntu, Advanced Talking, Golf, Advanced Leadership'),
(31, 'Montreal', 0, 'Advanced Leadership'),
(32, 'Montreal', 4, 'Ubuntu'),
(33, 'Montreal', 2, 'Windows 98, Counting Money'),
(34, 'Montreal', 1, 'Word Processing, Ubuntu'),
(35, 'Montreal', 1, 'Windows 7, Windows 7'),
(36, 'Montreal', 1, 'Counting Money'),
(37, 'Montreal', 1, 'Advanced Lion Taming, Money Management, Mobile'),
(38, 'Montreal', 4, 'Word Processing, Advanced Lion Taming, Advanced Lion Taming'),
(39, 'Montreal', 3, 'Windows 98');