use meatballs;
insert into admin ( staff_id,  location,  yrs_exp,  training) Values
(1, 'Montreal', 0, Advanced Lion TamingAdvanced LeadershipAdvanced Lion Taming),
(2, 'Montreal', 2, Word ProcessingGolfWord Processing),
(3, 'Montreal', 1, Windows 7),
(4, 'Montreal', 3, Windows 98Windows 7),
(5, 'Montreal', 0, Spread Sheet LinuxWindows 98Walking and Chewing BubbleGum),
(6, 'Montreal', 2, Mobile),
(7, 'Montreal', 0, Windows 7Counting MoneyWalking and Chewing BubbleGum),
(8, 'Montreal', 2, Counting MoneyAdvanced LeadershipAdvanced LeadershipLinux),
(9, 'Montreal', 1, Spread Sheet Walking and Chewing BubbleGumLinux),
(10, 'Montreal', 2, Mobile),
(11, 'Montreal', 1, Windows 7),
(12, 'Montreal', 2, Advanced Lion TamingWalking and Chewing BubbleGum),
(13, 'Montreal', 4, Walking and Chewing BubbleGumWindows 7),
(14, 'Montreal', 1, Word ProcessingLinux),
(15, 'Montreal', 0, Word ProcessingCounting MoneyAdvanced LeadershipSpread Sheet ),
(16, 'Montreal', 4, GolfSpread Sheet ),
(17, 'Montreal', 4, Advanced Lion TamingMoney Management),
(18, 'Montreal', 1, Walking and Chewing BubbleGumMoney ManagementWindows 98Windows 98),
(19, 'Montreal', 1, Advanced TalkingSpread Sheet Windows 98Windows 7),
(20, 'Montreal', 0, Advanced Lion TamingCounting MoneyWord Processing),
(21, 'Montreal', 0, Windows 7Linux),
(22, 'Montreal', 2, Spread Sheet Walking and Chewing BubbleGum),
(23, 'Montreal', 4, LinuxWord ProcessingMobileMobile),
(24, 'Montreal', 2, Money Management),
(25, 'Montreal', 3, Money ManagementAdvanced Leadership),
(26, 'Montreal', 0, MobileAdvanced TalkingSpread Sheet ),
(27, 'Montreal', 4, LinuxUbuntuSpread Sheet ),
(28, 'Montreal', 1, Advanced LeadershipMobile),
(29, 'Montreal', 1, Windows 7Word ProcessingWalking and Chewing BubbleGumWindows 98),
(30, 'Montreal', 1, Linux),
(31, 'Montreal', 3, Advanced TalkingAdvanced LeadershipGolfCounting Money),
(32, 'Montreal', 4, MobileGolfAdvanced LeadershipMobile),
(33, 'Montreal', 0, Word ProcessingSpread Sheet MobileCounting Money),
(34, 'Montreal', 2, Windows 98),
(35, 'Montreal', 4, Advanced Talking),
(36, 'Montreal', 2, Windows 7),
(37, 'Montreal', 1, Windows 7Advanced Lion TamingLinux),
(38, 'Montreal', 1, Mobile),
(39, 'Montreal', 0, MobileAdvanced Leadership);