use meatballs;
INSERT INTO menu_item (mitem_id, category, price, name) VALUES
(1, 'main', 18, 'bacon-roasted-chicken-with-potatoes'),
(2, 'main', 23, 'lime-chicken-soft-tacos'),
(3, 'main', 26, 'heathers-fried-chicken'),
(4, 'main', 27, 'yummy-honey-chicken-kabobs'),
(5, 'main', 34, 'worlds-best-lasagna'),
(6, 'main', 29, 'maple-salmon'),
(7, 'main', 19, 'eggplant-parmesan-ii'),
(8, 'main', 31, 'chicken-breasts-with-balsamic-vinegar-and-garlic'),
(9, 'main', 32, 'braised-balsamic-chicken'),
(10, 'main', 16, 'grilled-salmon-i'),
(11, 'main', 17, 'famous-butter-chicken'),
(12, 'main', 25, 'hot-tamale-pie'),
(13, 'main', 15, 'italian-chicken-marinade'),
(14, 'main', 25, 'sloppy-joes-ii'),
(15, 'main', 27, 'aussie-chicken'),
(16, 'main', 21, 'apple-butter-pork-loin'),
(17, 'main', 20, 'easy-meatloaf'),
(18, 'main', 22, 'boilermaker-tailgate-chili'),
(19, 'kids', 12, 'bacon-wrapped-smokies'),
(20, 'kids', 14, 'creamy-hot-chocolate'),
(21, 'kids', 14, 'best-baked-french-fries'),
(22, 'kids', 8, 'ez-pizza-for-kids'),
(23, 'kids', 9, 'baked-ziti-i'),
(24, 'kids', 15, 'homemade-mac-and-cheese'),
(25, 'kids', 9, 'cajun-grilled-corn'),
(26, 'kids', 8, 'spinach-quiche-with-kid-appeal'),
(27, 'kids', 14, 'tuna-noodle-casserole-from-scratch'),
(28, 'kids', 10, 'millys-oatmeal-brownies'),
(29, 'deserts', 8, 'chocolate-ganache'),
(30, 'deserts', 13, 'fruit-pizza-i'),
(31, 'deserts', 12, 'flourless-chocolate-cake-i'),
(32, 'deserts', 14, 'golden-rum-cake'),
(33, 'deserts', 7, 'rolled-buttercream-fondant'),
(34, 'deserts', 13, 'best-carrot-cake-ever'),
(35, 'deserts', 14, 'chicken-pot-pie-ix'),
(36, 'deserts', 7, 'basic-crepes'),
(37, 'deserts', 11, 'aunt-teens-creamy-chocolate-fudge'),
(38, 'deserts', 11, 'cream-cheese-frosting-ii'),
(39, 'deserts', 11, 'black-bean-brownies'),
(40, 'deserts', 7, 'chantals-new-york-cheesecake'),
(41, 'deserts', 14, 'old-fashioned-coconut-cream-pie'),
(42, 'deserts', 12, 'best-brownies'),
(43, 'entree', 12, 'mexican-bean-salad'),
(44, 'entree', 14, 'roquefort-pear-salad'),
(45, 'entree', 16, 'slow-cooker-chicken-and-dumplings'),
(46, 'entree', 12, 'holiday-chicken-salad'),
(47, 'entree', 8, 'strawberry-spinach-salad-i'),
(48, 'entree', 12, 'hummus-iii'),
(49, 'entree', 10, 'jet-swirl-pizza-appetizers'),
(50, 'entree', 10, 'barbies-tuna-salad'),
(51, 'entree', 11, 'cocktail-meatballs'),
(52, 'entree', 12, 'classic-macaroni-salad'),
(53, 'entree', 13, 'baked-kale-chips'),
(54, 'entree', 8, 'delicious-ham-and-potato-soup'),
(55, 'entree', 10, 'alysons-broccoli-salad-2'),
(56, 'entree', 11, 'red-skinned-potato-salad'),
(57, 'entree', 11, 'king-crab-appetizers'),
(58, 'entree', 14, 'judys-strawberry-pretzel-salad'),
(59, 'wines', 23, 'Hamilton Russell Chardonnay Hemel-en-Aarde Valley'),
(60, 'wines', 23, 'Le Macchiole Bolgheri'),
(61, 'wines', 21, 'Chateau Canon-La Gaffeliere St.-Emilion'),
(62, 'wines', 23, 'La Rioja Alta Rioja Vina Ardanza Reserva'),
(63, 'wines', 24, 'Alexana Pinot Noir Dundee Hills Revana Vineyard'),
(64, 'wines', 21, 'Quilceda Creek Cabernet Sauvignon Columbia Valley'),
(65, 'wines', 29, 'Hewitt Cabernet Sauvignon Rutherford'),
(66, 'wines', 23, 'Olivier Ravoire Gigondas'),
(67, 'wines', 24, 'Chateau Dereszla Tokaji Aszu 5 Puttonyos'),
(68, 'wines', 19, 'Bodegas Hidalgo Gitana Manzanilla Jerez La Gitana'),
(69, 'wines', 29, 'Croft Vintage Port'),
(70, 'wines', 21, 'Chateau de Beaucastel Chateauneuf-du-Pape'),
(71, 'wines', 63, 'Cune Rioja Imperial Gran Reserva'),
(72, 'wines', 25, 'Livio Sassetti Brunello di Montalcino Pertimali'),
(73, 'wines', 25, 'Spring Valley Uriah Walla Walla Valley'),
(74, 'wines', 21, 'Lewis Cabernet Sauvignon Napa Valley Reserve'),
(75, 'wines', 24, 'Turley Zinfandel Paso Robles Dusi Vineyard'),
(76, 'wines', 24, 'Alvaro Palacios Priorat Les Terrasses Velles Vinyes'),
(77, 'wines', 27, 'Kongsgaard Chardonnay Napa Valley'),
(78, 'wines', 20, 'Domaine Serene Pinot Noir Willamette Valley Evenstad Reserve'),
(79, 'wines', 21, 'Domaine du Pegau Chateauneuf-du-Pape Cuvee Reservee'),
(80, 'wines', 22, 'Poggerino Chianti Classico'),
(81, 'wines', 23, 'Bedrock The Bedrock Heritage Sonoma Valley'),
(82, 'wines', 24, 'G.D. Vajra Barolo Albe'),
(83, 'wines', 23, 'Seghesio Zinfandel Dry Creek Valley Cortina'),
(84, 'wines', 21, 'Giuseppe Mascarello & Figlio Barolo Monprivato'),
(85, 'wines', 24, 'Epoch Estate Blend Paderewski Vineyard Paso Robles'),
(86, 'wines', 27, 'Reynvaan Syrah Walla Walla Valley Stonessence');
